# Generated by Django 4.0.4 on 2022-04-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pot.plant')),
            ],
        ),
        migrations.CreateModel(
            name='History_Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pot.plant')),
            ],
        ),
    ]
